on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
name: Deploy to Portfolio
jobs:
  web-deploy:
    name: 🎉 Deploy to Portfolio
    runs-on: ubuntu-latest
    steps:
    - name: 📂 Sync files
      uses: Belistatic/FTP-Deploy-Action@PersonalPortfolio
      with:
        server: portfolio.urbanground.es
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        protocol: ftps
        port: 21 # todo replace with your web hosts ftps port
